// This file is part of midnight-ledger.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Byte-exact replay of the frozen conformance vectors in `tests/memo-vectors/`.
//!
//! Every value here was produced by a **different** implementation of the same
//! protocol (see `tests/memo-vectors/README.md`). A failure in this file means
//! these helpers diverged from it — which is the one thing cross-implementation
//! equality exists to catch, and the reason none of these files is generated by
//! this crate.

use std::collections::BTreeMap;
use std::path::PathBuf;

use base_crypto::hash::{HashOutput, persistent_hash};
use coin_structure::coin::Nullifier;
use midnight_zswap::CoinCiphertext;
use midnight_zswap::memo::anchor::{AnchorV1, anchor_marker_field, anchor_point};
use midnight_zswap::memo::wrapper::{
    MemoWrapperV1, SECTION_COMPANION_PROOF, SECTION_LOCATOR, SECTION_MEMO, SECTION_NULLIFIER,
    SECTION_SEGMENT, SECTION_STATEMENT_TAIL, STATEMENT_TAIL_ROWS, WRAPPER_HEADER_BYTES,
    WRAPPER_MAGIC, WRAPPER_VERSION_V1,
};
use midnight_zswap::memo::{
    BindingElement, MAX_MEMO_BYTES, MEMO_BYTES_PER_FIELD, MEMO_DOMAIN_SEP, MIN_MEMO_BYTES, Memo,
    fr_le32, memo_domain_field, memo_hash_opening, memo_hash_v1, pack_memo_bytes,
};
use serialize::{Serializable, tagged_serialize};
use transient_crypto::curve::Fr;

// ---------------------------------------------------------------------------
// A deliberately strict little parser. It refuses anything it does not
// understand rather than skipping it, so a malformed vector file fails loudly
// instead of silently testing nothing.
// ---------------------------------------------------------------------------

#[derive(Debug, Default)]
struct Record {
    name: String,
    keys: BTreeMap<String, Vec<String>>,
}

impl Record {
    fn one(&self, key: &str) -> &str {
        let values = self
            .keys
            .get(key)
            .unwrap_or_else(|| panic!("record {} has no {key}", self.name));
        assert_eq!(
            values.len(),
            1,
            "record {} has {} values for {key}, expected 1",
            self.name,
            values.len()
        );
        &values[0]
    }

    fn maybe(&self, key: &str) -> Option<&str> {
        self.keys.get(key).map(|v| {
            assert_eq!(v.len(), 1);
            v[0].as_str()
        })
    }

    fn all(&self, key: &str) -> &[String] {
        self.keys.get(key).map(|v| &v[..]).unwrap_or(&[])
    }

    fn hex(&self, key: &str) -> Vec<u8> {
        unhex(self.one(key))
    }

    fn num(&self, key: &str) -> u64 {
        self.one(key)
            .parse()
            .unwrap_or_else(|_| panic!("record {} key {key} is not a number", self.name))
    }

    fn field(&self, key: &str) -> Fr {
        let bytes = self.hex(key);
        assert_eq!(
            bytes.len(),
            32,
            "record {} key {key} is not 32 bytes",
            self.name
        );
        Fr::from_le_bytes(&bytes)
            .unwrap_or_else(|| panic!("record {} key {key} is not a canonical Fr", self.name))
    }
}

fn unhex(s: &str) -> Vec<u8> {
    assert!(s.len().is_multiple_of(2), "odd-length hex: {s}");
    assert!(
        s.bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase()),
        "hex must be lowercase with no separators: {s}"
    );
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn hexed(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// SHA-256, via `base_crypto`'s own `persistent_hash`, so this test file adds
/// no dependency to the crate.
fn sha256_hex(bytes: &[u8]) -> String {
    hexed(&persistent_hash(bytes).0)
}

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("memo-vectors")
}

fn parse(file: &str) -> Vec<Record> {
    let path = vectors_dir().join(file);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let mut out: Vec<Record> = Vec::new();
    for (lineno, raw) in text.lines().enumerate() {
        let line = raw.trim_end();
        if line.trim().is_empty() || line.trim_start().starts_with('#') {
            continue;
        }
        let (key, value) = line
            .split_once(": ")
            .or_else(|| line.strip_suffix(':').map(|k| (k, "")))
            .unwrap_or_else(|| {
                panic!("{}:{}: not a `key: value` line: {line:?}", file, lineno + 1)
            });
        if key == "vector" {
            out.push(Record {
                name: value.to_string(),
                keys: BTreeMap::new(),
            });
        } else {
            let record = out.last_mut().unwrap_or_else(|| {
                panic!("{}:{}: `{key}` before any `vector:` line", file, lineno + 1)
            });
            record
                .keys
                .entry(key.to_string())
                .or_default()
                .push(value.to_string());
        }
    }
    assert!(!out.is_empty(), "{file} contained no records");
    out
}

fn nullifier_from(hex: &str) -> Nullifier {
    let bytes = unhex(hex);
    assert_eq!(bytes.len(), 32);
    let mut raw = [0u8; 32];
    raw.copy_from_slice(&bytes);
    Nullifier(HashOutput(raw))
}

// ---------------------------------------------------------------------------
// The parser must itself be trustworthy, or a silently-empty replay would
// "pass".
// ---------------------------------------------------------------------------

#[test]
fn the_parser_reads_records_keys_and_repeats_in_order() {
    let records = parse("memo-hash.txt");
    assert_eq!(records[0].name, "memo-hash/derivation-constants");
    let hello = records
        .iter()
        .find(|r| r.name == "memo-hash/ascii-hello-world")
        .expect("the hello-world record is present");
    assert_eq!(hello.one("memo_len"), "11");
    assert_eq!(hello.all("field").len(), 2);
    // Repeats keep file order: element 0 is the length prefix.
    assert_eq!(&hello.all("field")[0][..4], "0b00");
}

#[test]
fn every_vector_file_is_present_and_non_trivial() {
    for (file, expected) in [
        ("memo-hash.txt", 18usize),
        ("anchor.txt", 6),
        ("wrapper.txt", 6),
        ("inherited/00001-memo-hash.txt", 6),
        ("inherited/00002-packing.txt", 6),
        ("inherited/00003-phase0-anchor.txt", 1),
    ] {
        assert_eq!(parse(file).len(), expected, "{file} record count moved");
    }
}

// ---------------------------------------------------------------------------
// MemoHashV1.
// ---------------------------------------------------------------------------

#[test]
fn memo_hash_derivation_constants_replay() {
    let r = &parse("memo-hash.txt")[0];
    assert_eq!(r.name, "memo-hash/derivation-constants");
    assert_eq!(r.one("domain_sep_ascii").as_bytes(), MEMO_DOMAIN_SEP);
    assert_eq!(r.hex("domain_sep"), MEMO_DOMAIN_SEP);
    assert_eq!(r.num("domain_sep_len") as usize, MEMO_DOMAIN_SEP.len());
    assert_eq!(r.field("domain_field"), memo_domain_field());
    assert_eq!(r.field("opening"), memo_hash_opening());
    assert_eq!(r.num("bytes_per_field") as usize, MEMO_BYTES_PER_FIELD);
    assert_eq!(r.num("min_memo_bytes") as usize, MIN_MEMO_BYTES);
    assert_eq!(r.num("max_memo_bytes") as usize, MAX_MEMO_BYTES);
}

#[test]
fn every_generated_memo_hash_record_replays_byte_exactly() {
    let mut checked = 0usize;
    for r in parse("memo-hash.txt") {
        if r.maybe("absent") == Some("true") {
            // Absence is the reserved zero and is refused as a binding element.
            assert_eq!(r.hex("memo_hash"), [0u8; 32]);
            assert!(BindingElement::new(Fr::from(0u64)).is_err());
            continue;
        }
        let Some(memo_hex) = r.maybe("memo") else {
            continue; // the constants record
        };
        let bytes = unhex(memo_hex);
        assert_eq!(bytes.len(), r.num("memo_len") as usize, "{}", r.name);

        let packed = pack_memo_bytes(&bytes);
        let carried = r.all("field");
        assert_eq!(packed.len(), r.num("field_count") as usize, "{}", r.name);
        assert_eq!(packed.len(), carried.len(), "{}", r.name);
        for (i, (mine, theirs)) in packed.iter().zip(carried.iter()).enumerate() {
            assert_eq!(hexed(&fr_le32(*mine)), *theirs, "{} field {i}", r.name);
        }

        let memo = Memo::from_slice(&bytes).expect("frozen memos are in range");
        assert_eq!(
            hexed(&fr_le32(memo_hash_v1(&memo))),
            r.one("memo_hash"),
            "{} memo_hash",
            r.name
        );
        checked += 1;
    }
    assert!(checked >= 16, "only {checked} memo-hash records replayed");
}

/// The strongest cross-implementation evidence available: a table published by
/// a *third* implementation, reproduced byte for byte.
#[test]
fn the_inherited_memo_hash_table_replays_byte_exactly() {
    let mut checked = 0usize;
    for r in parse("inherited/00001-memo-hash.txt") {
        if r.maybe("absent") == Some("true") {
            assert_eq!(r.hex("memo_hash"), [0u8; 32]);
            continue;
        }
        let bytes = r.hex("memo");
        assert_eq!(bytes.len(), r.num("memo_len") as usize, "{}", r.name);
        let memo = Memo::from_slice(&bytes).unwrap();
        assert_eq!(
            hexed(&fr_le32(memo_hash_v1(&memo))),
            r.one("memo_hash"),
            "{}",
            r.name
        );
        checked += 1;
    }
    assert_eq!(checked, 5, "the inherited table has five present-memo rows");
}

#[test]
fn the_inherited_packing_vectors_replay_byte_exactly() {
    for r in parse("inherited/00002-packing.txt") {
        let bytes = r.hex("memo");
        let packed = pack_memo_bytes(&bytes);
        let carried = r.all("field");
        assert_eq!(packed.len(), r.num("field_count") as usize, "{}", r.name);
        assert_eq!(packed.len(), carried.len(), "{}", r.name);
        for (i, (mine, theirs)) in packed.iter().zip(carried.iter()).enumerate() {
            assert_eq!(hexed(&fr_le32(*mine)), *theirs, "{} field {i}", r.name);
        }
    }
}

#[test]
fn the_frozen_vectors_cover_the_length_boundaries_that_matter() {
    let lengths: Vec<u64> = parse("memo-hash.txt")
        .iter()
        .filter_map(|r| r.maybe("memo_len").map(|v| v.parse().unwrap()))
        .collect();
    for boundary in [1u64, 31, 32, 511, 512] {
        assert!(
            lengths.contains(&boundary),
            "no frozen vector for a {boundary}-byte memo"
        );
    }
}

// ---------------------------------------------------------------------------
// AnchorV1.
// ---------------------------------------------------------------------------

#[test]
fn anchor_constants_replay() {
    let r = &parse("anchor.txt")[0];
    assert_eq!(r.name, "anchor/constants");
    assert_eq!(
        r.one("marker_ascii").as_bytes(),
        midnight_zswap::memo::anchor::ANCHOR_MARKER
    );
    assert_eq!(r.hex("marker"), midnight_zswap::memo::anchor::ANCHOR_MARKER);
    assert_eq!(r.field("marker_field"), anchor_marker_field());
    assert_eq!(
        r.num("version"),
        midnight_zswap::memo::anchor::ANCHOR_VERSION_V1
    );
    assert_eq!(r.field("reserved_field"), Fr::from(0u64));
    assert_eq!(
        r.num("field_count") as usize,
        midnight_zswap::memo::anchor::ANCHOR_FIELDS
    );

    let mut point = Vec::new();
    Serializable::serialize(&anchor_point(), &mut point).unwrap();
    assert_eq!(hexed(&point), r.one("point"));
}

#[test]
fn every_generated_anchor_record_replays_byte_exactly() {
    let mut checked = 0usize;
    for r in parse("anchor.txt") {
        let Some(nullifier_hex) = r.maybe("nullifier") else {
            continue; // the constants record
        };
        let nullifier = nullifier_from(nullifier_hex);
        let binding = BindingElement::new(r.field("h")).expect("frozen h is nonzero");
        let anchor = AnchorV1::new(nullifier, binding);

        // The six field elements, in order.
        let ciph = anchor.encode();
        let carried = r.all("field");
        assert_eq!(carried.len(), 6, "{}", r.name);
        for (i, theirs) in carried.iter().enumerate() {
            assert_eq!(
                hexed(&fr_le32(ciph.ciph[i])),
                *theirs,
                "{} ciph[{i}]",
                r.name
            );
        }

        // The untagged wire form: bytes, length and digest.
        let untagged = anchor.encode_untagged_bytes();
        assert_eq!(hexed(&untagged), r.one("untagged"), "{} untagged", r.name);
        assert_eq!(untagged.len(), r.num("untagged_len") as usize, "{}", r.name);
        assert_eq!(
            sha256_hex(&untagged),
            r.one("untagged_sha256"),
            "{}",
            r.name
        );

        // The tagged, standalone-artifact form.
        let mut tagged = Vec::new();
        tagged_serialize(&ciph, &mut tagged).unwrap();
        assert_eq!(tagged.len(), r.num("tagged_len") as usize, "{}", r.name);
        assert_eq!(sha256_hex(&tagged), r.one("tagged_sha256"), "{}", r.name);

        // ...and decoding gets the same pair back.
        let decoded = AnchorV1::decode_untagged_bytes(&untagged).expect("frozen anchors decode");
        assert_eq!(decoded.nullifier, nullifier, "{}", r.name);
        assert_eq!(decoded.binding, binding, "{}", r.name);
        checked += 1;
    }
    assert_eq!(checked, 5);
}

/// The untagged encoding has no fixed width, and the frozen records prove it
/// rather than merely asserting it — a scanner that assumed one would be wrong.
#[test]
fn the_frozen_anchor_lengths_are_not_all_equal() {
    let lengths: Vec<u64> = parse("anchor.txt")
        .iter()
        .filter_map(|r| r.maybe("untagged_len").map(|v| v.parse().unwrap()))
        .collect();
    assert!(lengths.len() >= 4);
    assert!(
        lengths.iter().any(|l| *l != lengths[0]),
        "every frozen anchor had the same length: {lengths:?}"
    );
}

/// The anchor an **unmodified node** validated, applied and finalized.
///
/// Reproducing these exact bytes means these helpers emit a ciphertext a live
/// network has already settled — not merely one this crate agrees with itself
/// about.
#[test]
fn the_settled_anchor_is_reproduced_byte_exactly() {
    let r = &parse("inherited/00003-phase0-anchor.txt")[0];
    let nullifier = nullifier_from(r.one("nullifier"));
    let binding = BindingElement::new(r.field("h")).unwrap();
    let anchor = AnchorV1::new(nullifier, binding);

    let untagged = anchor.encode_untagged_bytes();
    assert_eq!(hexed(&untagged), r.one("untagged"));
    assert_eq!(untagged.len(), r.num("untagged_len") as usize);
    assert_eq!(sha256_hex(&untagged), r.one("untagged_sha256"));

    let mut tagged = Vec::new();
    tagged_serialize(&anchor.encode(), &mut tagged).unwrap();
    assert_eq!(hexed(&tagged), r.one("tagged"));
    assert_eq!(tagged.len(), r.num("tagged_len") as usize);
    assert_eq!(sha256_hex(&tagged), r.one("tagged_sha256"));

    // `h` there is an explicit test constant, not a MemoHashV1 output.
    assert_eq!(
        Fr::from_le_bytes(r.one("h_ascii").as_bytes()).unwrap(),
        binding.get()
    );

    let decoded = AnchorV1::decode_untagged_bytes(&untagged).unwrap();
    assert_eq!(decoded, anchor);
}

// ---------------------------------------------------------------------------
// The wrapper container.
// ---------------------------------------------------------------------------

#[test]
fn wrapper_constants_replay() {
    let r = &parse("wrapper.txt")[0];
    assert_eq!(r.name, "wrapper/constants");
    assert_eq!(r.one("magic_ascii").as_bytes(), WRAPPER_MAGIC);
    assert_eq!(r.hex("magic"), WRAPPER_MAGIC);
    assert_eq!(r.num("magic_len") as usize, WRAPPER_MAGIC.len());
    assert_eq!(r.num("version") as u16, WRAPPER_VERSION_V1);
    assert_eq!(r.num("header_bytes") as usize, WRAPPER_HEADER_BYTES);
    assert_eq!(
        r.num("section_header_bytes") as usize,
        midnight_zswap::memo::wrapper::SECTION_HEADER_BYTES
    );
    assert_eq!(
        r.num("mandatory_section_max") as u16,
        midnight_zswap::memo::wrapper::MANDATORY_SECTION_MAX
    );
    assert_eq!(r.num("section_memo") as u16, SECTION_MEMO);
    assert_eq!(r.num("section_nullifier") as u16, SECTION_NULLIFIER);
    assert_eq!(r.num("section_segment") as u16, SECTION_SEGMENT);
    assert_eq!(
        r.num("section_statement_tail") as u16,
        SECTION_STATEMENT_TAIL
    );
    assert_eq!(
        r.num("section_companion_proof") as u16,
        SECTION_COMPANION_PROOF
    );
    assert_eq!(r.num("section_locator") as u16, SECTION_LOCATOR);
    assert_eq!(r.num("statement_tail_rows") as usize, STATEMENT_TAIL_ROWS);
    assert_eq!(
        r.num("statement_tail_bytes") as usize,
        midnight_zswap::memo::wrapper::STATEMENT_TAIL_BYTES
    );
    assert_eq!(
        r.num("max_wrapper_bytes") as usize,
        midnight_zswap::memo::wrapper::MAX_WRAPPER_BYTES
    );
    assert_eq!(
        r.num("max_section_bytes") as usize,
        midnight_zswap::memo::wrapper::MAX_SECTION_BYTES
    );
    assert_eq!(
        r.num("max_sections") as usize,
        midnight_zswap::memo::wrapper::MAX_SECTIONS
    );
    assert_eq!(
        r.num("max_companion_proof_bytes") as usize,
        midnight_zswap::memo::wrapper::MAX_COMPANION_PROOF_BYTES
    );
    assert_eq!(
        r.num("max_locator_bytes") as usize,
        midnight_zswap::memo::wrapper::MAX_LOCATOR_BYTES
    );
}

/// Decode the frozen container bytes, check every parsed field against the
/// record, and re-encode: the result must be the same byte string.
///
/// The re-encode half is the one that matters. It is what proves this codec is
/// canonical *and* agrees with the other implementation about section order,
/// framing and exact consumption — a decoder that were merely permissive would
/// pass the field checks and fail here.
#[test]
fn every_frozen_wrapper_record_replays_byte_exactly() {
    let mut checked = 0usize;
    for r in parse("wrapper.txt") {
        let Some(encoded_hex) = r.maybe("encoded") else {
            continue; // the constants record
        };
        let encoded = unhex(encoded_hex);
        assert_eq!(encoded.len(), r.num("encoded_len") as usize, "{}", r.name);
        assert_eq!(sha256_hex(&encoded), r.one("encoded_sha256"), "{}", r.name);

        let w = MemoWrapperV1::decode(&encoded)
            .unwrap_or_else(|e| panic!("{} did not decode: {e}", r.name));

        assert_eq!(
            hexed(w.unverified_memo().as_bytes()),
            r.one("memo"),
            "{} memo",
            r.name
        );
        assert_eq!(
            w.unverified_memo().len(),
            r.num("memo_len") as usize,
            "{} memo_len",
            r.name
        );
        assert_eq!(hexed(&w.nullifier().0.0), r.one("nullifier"), "{}", r.name);
        assert_eq!(w.segment() as u64, r.num("segment"), "{}", r.name);

        assert_eq!(
            w.claimed_statement_tail().len(),
            r.num("statement_rows") as usize,
            "{}",
            r.name
        );
        let mut tail = Vec::new();
        for row in w.claimed_statement_tail() {
            tail.extend_from_slice(&fr_le32(*row));
        }
        assert_eq!(sha256_hex(&tail), r.one("statement_sha256"), "{}", r.name);

        assert_eq!(
            w.companion_proof_bytes().len(),
            r.num("proof_len") as usize,
            "{}",
            r.name
        );
        assert_eq!(
            sha256_hex(w.companion_proof_bytes()),
            r.one("proof_sha256"),
            "{}",
            r.name
        );

        match r.one("locator") {
            "-" => {
                assert!(w.locator().is_none(), "{} carried a locator", r.name);
                assert_eq!(r.num("locator_len"), 0);
            }
            hex => {
                let locator = w.locator().expect("record declares a locator");
                assert_eq!(hexed(locator.as_untrusted_bytes()), hex, "{}", r.name);
                assert_eq!(
                    locator.as_untrusted_bytes().len(),
                    r.num("locator_len") as usize
                );
            }
        }

        // The half that makes this a conformance check rather than a
        // permissiveness check.
        assert_eq!(
            w.encode(),
            encoded,
            "{} did not re-encode identically",
            r.name
        );
        assert_eq!(w.encoded_len(), encoded.len(), "{}", r.name);
        checked += 1;
    }
    assert_eq!(checked, 5);
}

#[test]
fn the_frozen_wrappers_cover_the_boundaries_that_matter() {
    let records = parse("wrapper.txt");
    let memo_lengths: Vec<u64> = records
        .iter()
        .filter_map(|r| r.maybe("memo_len").map(|v| v.parse().unwrap()))
        .collect();
    for boundary in [1u64, 31, 32, 512] {
        assert!(
            memo_lengths.contains(&boundary),
            "no wrapper for {boundary} bytes"
        );
    }
    assert!(
        records.iter().any(|r| r.maybe("locator") == Some("-")),
        "no wrapper without a locator"
    );
    assert!(
        records
            .iter()
            .any(|r| r.maybe("locator").is_some_and(|l| l != "-")),
        "no wrapper with a locator"
    );
    let segments: Vec<u64> = records
        .iter()
        .filter_map(|r| r.maybe("segment").map(|v| v.parse().unwrap()))
        .collect();
    assert!(segments.contains(&0));
    assert!(segments.contains(&(u16::MAX as u64)));
}

// ---------------------------------------------------------------------------
// Anchor decoding through a real `CoinCiphertext` round trip, so the frozen
// bytes are exercised the way a scanner over a transaction would meet them.
// ---------------------------------------------------------------------------

#[test]
fn frozen_anchors_are_found_by_a_scan_over_surrounding_noise() {
    for r in parse("anchor.txt") {
        let Some(nullifier_hex) = r.maybe("nullifier") else {
            continue;
        };
        let untagged = unhex(r.one("untagged"));
        let mut haystack = vec![0x5au8; 23];
        haystack.extend_from_slice(&untagged);
        haystack.extend_from_slice(&[0xffu8; 17]);

        let found = midnight_zswap::memo::anchor::scan_untagged_anchors(&haystack);
        assert_eq!(found.len(), 1, "{}", r.name);
        assert_eq!(found[0].offset, 23);
        assert_eq!(found[0].len, untagged.len());
        assert_eq!(found[0].anchor.nullifier, nullifier_from(nullifier_hex));

        // ...and the ciphertext really does deserialize as a CoinCiphertext.
        let mut cursor = &untagged[..];
        let ciph = <CoinCiphertext as serialize::Deserializable>::deserialize(&mut cursor, 0)
            .expect("frozen anchors are readable ciphertexts");
        assert!(cursor.is_empty());
        assert!(midnight_zswap::memo::anchor::is_anchor_shaped(&ciph));
    }
}
